#!/bin/bash
set -e

function config {
  /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME $@
}

echo "dotfiles setup"

if [ -d $HOME/.cfg ]; then
  echo "Dotfiles already setup, update the usual way"
else
  echo "Installing dotfiles"
  git clone --bare gith@github.com:b2l/cfg.git $HOME/.cfg

  mkdir -p .config-backup
  config checkout
  if [ $? = 0 ]; then
    echo "Checked out config.";
  else
    echo "Backing up pre-existing dot files.";
    config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .config-backup/{}
  fi;
  config checkout
  config config status.showUntrackedFiles no
fi
